### PR TITLE
Fix comma/quotes

### PR DESCRIPTION
**Pull request by mOctave**
Commas should go inside quotes, I think.

### CODE REVIEW

**Comment by a-random-lemurian** [comment]
No, commas don't go into quotes. The commas are being used to indicate that there are several quotes. Putting the commas inside would make the rule grammatically incorrect.

**Comment by mOctave** [comment]
Even if there are several, distinct quotes, as far as I know the rule is still to always put commas and periods inside, while exclamation marks and question marks can go outside if they aren't part of whatever is in quotes.
Screenshot 2022-11-21 at 6 06 10 PM

**Comment by mOctave** [comment]
Ah, wait a second. It appears that this rules is applicable for US grammar but not for British grammar.
This might be where the confusion is coming from.

**Comment by a-random-lemurian** [comment]
> Ah, wait a second. It appears that this rules is applicable for US grammar but not for British grammar. This might be where the confusion is coming from.

This repository, consistent with Endless Sky's mission text, is written in American English with American spelling (with a few exceptions). So yes, you should hopefully understand it now.

**Comment by mOctave** [comment]
The way I understand it, the commas go _in_ "quotes," in American English with exactly ("one"), exception. In British English, "commas", go outside quotes, with a few exceptions. So the commas should be in quotes here after all, if it's supposed to be American English.

**Pull request closed without merging**
